### PR TITLE
Dependencies are not added if the bundableNode is a Workbench and the as...

### LINKED ISSUE #819: workbench-deps errors out when it shouldn't
Running `brjs workbench-deps fxtrader fxtrader tile` (or any other blade really) will give me this exception:

```
Error:
  org.bladerunnerjs.model.exception.ModelOperationException: org.bladerunnerjs.model.exception.UnresolvableRequirePathException: Source file 'caplinx/WebcentricManager' could not be found.

Caused By:
  org.bladerunnerjs.model.exception.UnresolvableRequirePathException: Source file 'caplinx/WebcentricManager' could not be found.

Stack Trace:
org.bladerunnerjs.model.exception.command.CommandOperationException: org.bladerunnerjs.model.exception.ModelOperationException: org.bladerunnerjs.model.exception.UnresolvableRequirePathException: Source file 'caplinx/WebcentricManager' could not be found.
        at org.bladerunnerjs.plugin.plugins.commands.standard.WorkbenchDepsCommand.doCommand(WorkbenchDepsCommand.java:76)
        at org.bladerunnerjs.plugin.utility.command.ArgsParsingCommandPlugin.doCommand(ArgsParsingCommandPlugin.java:45)
        at org.bladerunnerjs.plugin.proxy.VirtualProxyCommandPlugin.doCommand(VirtualProxyCommandPlugin.java:41)
        at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:21)
        at org.bladerunnerjs.model.BRJS.runCommand(BRJS.java:325)
        at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:25)
        at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:18)
        at org.bladerunnerjs.model.BRJS.runUserCommand(BRJS.java:330)
        at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:108)
        at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:59)
```

The file `caplinx/WebcentricManager` isn't actually used anywhere in the blade or in the workbench, and the workbench itself loads just fine in the browser (and the file isn't bundled there).
I get the same error when running `brjs bundle-deps ../apps/fxtrader/fxtrader-bladeset/blades/tile/workbench/`.

I also created a brand new blade and got the same issue.

Running `brjs dep-insight fxtrader caplinx/WebcentricManager` gives me this result:

```
Source module 'caplinx/WebcentricManager' dependencies found:
    +--- 'default-aspect/src/caplinx/WebcentricManager.js'
    |    \--- 'default-aspect/webcentric/layout/application.xml' (seed file)
    |    \--- 'default-aspect/src/caplinx/FXTraderApp.js' (*)
    |    |    \--- 'default-aspect/index.html' (seed file)
    |    \--- 'default-aspect/src/caplinx/menu/MenuActionHandler.js'

    (*) - subsequent instances not shown (use -A or --all to show)
```

So it's clear that the file isn't being referenced from the blades/workbenches.

### PR DESCRIPTION
**Pull request by ioanalianabalas**
Fixes #819.

### CODE REVIEW

File: brjs-core/src/main/java/org/bladerunnerjs/utility/deps/DependencyInfoFactory.java [hunk 1]
```diff
@@ -113,6 +115,9 @@ private static void addAssetLocationDependencies(DependencyAdder dependencyAdder
 		DependencyInfo dependencyInfo, AssetLocation assetLocation) throws ModelOperationException {
 		for(LinkedAsset resourceAsset : assetLocation.linkedAssets()) {
 			dependencyInfo.resourceAssets.add(resourceAsset);
+			if (bundlableNode instanceof Workbench && assetLocation.assetContainer() instanceof Aspect) {
```
Comment (dchambers) [inline brjs-core/src/main/java/org/bladerunnerjs/utility/deps/DependencyInfoFactory.java]: Although I'm happy to incur some technical debt here, we should probably add a comment like:

```js
// TODO: the need for this code shows that our interfaces are incorrectly abstracted, which we should fix at some point
```

I assume too that we need this comment repeated in `BundleSetCreator`, or whatever the other class is that has a similar guard.

**Comment by ioanalianabalas** [comment]
@dchambers, the guard was only added in `DependencyInfoFactory` so I added the comment there now.
